### ISSUE TITLE
Avaliação do projeto

### ISSUE THREAD

**Issue by santos-fernando** [JupiChat/jupichat-project#1]
EQUIPE		NOTA: 1.3 (nota máxima da etapa: 1.5)
	João Pedro Schmitz
	Mário Fronza
	
ALOCAÇÃO DAS TAREFAS
Ok.

DIAGRAMA DE SEQUÊNCIA DEFINITIVO PROTOCOLO CLIENTE/SERVIDOR
Qual é a finalidade do parâmetro "message" que é enviado em todas as mensagens cliente->servidor?
Qual a diferença entre a mensagem "newContact" e "signup"?
Como será feita a manutenção do usuário online (keep alive)? Há uma mensagem específica ou qual é a mensagem que será usada para isso?

DIAGRAMA DE CLASSE SERVIDOR
Ok

DIAGRAMA DE SEQUÊNCIA PRELIMINAR CLIENTE/CLIENTE
Ok, pois o diagr. é preliminar. Sugestão é especificar também a mensagem de envio de arquivo, sendo que é necessário se preocupar em como vai ser o envio do arquivo (de uma só vez? em blocos?)

OBSERVAÇÕES
Os acadêmicos podem realizar os ajustes solicitados e fazer push até 11/11 ao meio-dia para melhorar a nota desta etapa.

**Comment by MarioFronza** [comment]
Qual é a finalidade do parâmetro "message" que é enviado em todas as mensagens cliente->servidor?

R: 
O parâmetro "message" específica a intenção que o cliente tem em relação ao servidor, por exemplo, o seguinte JSON retrata o momento do cadastro do usuário no servidor (signup). 

```javascript
{
     "message" : "signup",
     "user" : {
		"nickname" : "MarioFronza",
		"email" : "mario@teste.com",
		"password" : "123123",
		"birth" : "04/06/1999"
	}
}
```

Neste objeto está contido os dados da mensagem (intenção) e os dados do usuário que serão cadastrados no banco de dados. O objetivo é facilitar a interpretação do servidor ao receber diferentes tipos de mensagens.

Os tipos de mensagem serão: 

- signup
- signin
- signout
- createContact
- removeContact
- updateUser
- getAllContacts
- online

---

Qual a diferença entre a mensagem "newContact" e "signup"?

R: 
A mensagem “createContact” é disparada quando o cliente deseja adicionar um novo contato em sua lista. 

Exemplo: 


```javascript
{
     "message" : "createContact",
     "user" : {
          "email" : "contact@teste.com",
     }
}
```

O cliente envia a mensagem “signup” quando deseja criar uma conta. 

Exemplo: 


```javascript
 {
     "message" : "signup",
     "user" : {
          "nickname" : "JoaoPedro",
          "email" : "joao@teste.com",
         "password" : "123123",
          "birth" : "04/06/2000"
     }
}

```

---

Como será feita a manutenção do usuário online (keep alive)? Há uma mensagem específica ou qual é a mensagem que será usada para isso?

R:
No momento em que o cliente realizar um cadastro, ou se autenticar na aplicação, o servidor irá gravar no banco de dados o seu status como ONLINE, e sempre que outro cliente requisitar uma lista de contatos, o status de cada contato estará presente nesta requisição. 

Quando o usuário deslogar da aplicação, o cliente irá enviar uma mensagem “signout” para o servidor trocar o seu status para OFFLINE. 

Além disso, o cliente irá enviar para o servidor de tempos em tempos  uma mensagem “online”, informando que está ativo. 

O Servidor de tempos em tempos irá verificar se um cliente parou de enviar a mensagem “online” , e então, trocar seu status para offline.


link do diagrama: 
https://github.com/JupiChat/jupichat-project/blob/master/design-view/sequence/Sequence%20Diagram%20-%20keep%20alive.png

**Comment by santos-fernando** [comment]
Oi,
Favor incorporar estas definições no projeto (pode ser como comentários nos diagramas relacionados com as dúvidas). Deste modo as definições ficarão em um único local (no projeto) e não estarão espalhadas (no projeto + aqui nas issues). 
Quando pronto, fazer novo comentário aqui na issue para eu ser notificado e atualizar a nota.

**Comment by MarioFronza** [comment]
@santos-fernando Diagramas atualizados

**Comment by santos-fernando** [comment]
EQUIPE		NOTA FINAL: 1.5 (nota máxima da etapa: 1.5)
	João Pedro Schmitz
	Mário Fronza
	
DIAGRAMA DE SEQUÊNCIA DEFINITIVO PROTOCOLO CLIENTE/SERVIDOR
**[Revisão de 2019-11-11]** Ok, as solicitações foram esclarecidas e atualizadas no projeto.. 

OBSERVAÇÕES
**[Revisão de 2019-11-11]** A nota foi atualizada.
